'use client'
import Link from'next/link'
import{Trophy,Music2,Users,Star,DollarSign,Cpu,Bell,Cake,Send,TrendingUp,FileText,Zap,Shield,Brain}from'lucide-react'
const sections=[{title:'Modes',items:[{href:'/',icon:Zap,label:'Situation Room',desc:'JARVIS briefing & daily intelligence',color:'text-blue-400'},{href:'/sports',icon:Trophy,label:'Sports',desc:'1,572 athletes across all leagues',color:'text-orange-400'},{href:'/music',icon:Music2,label:'Music',desc:'540 artists & streaming intelligence',color:'text-purple-400'},{href:'/civilians',icon:Users,label:'Civilians',desc:'1,987 jewelry prospects',color:'text-yellow-400'},{href:'/influencers',icon:Star,label:'Influencers',desc:'140+ content creators',color:'text-pink-400'},{href:'/sales',icon:DollarSign,label:'Sales',desc:'Transactions & payouts',color:'text-green-400'},{href:'/system',icon:Cpu,label:'System',desc:'Health, auditor, QA Brain',color:'text-cyan-400'}]},{title:'Quick Access',items:[{href:'/alerts',icon:Bell,label:'Alerts',desc:'Contract & proactive alerts',color:'text-red-400'},{href:'/birthdays',icon:Cake,label:'Birthdays',desc:'Upcoming client birthdays',color:'text-pink-400'},{href:'/highlights',icon:TrendingUp,label:'Highlights',desc:'Signings & news',color:'text-cyan-400'},{href:'/outreach',icon:Send,label:'Outreach Queue',desc:'AI DMs awaiting approval',color:'text-blue-400'},{href:'/sports/draft',icon:FileText,label:'Draft Command Center',desc:'Big Board & prospects',color:'text-orange-400'}]},{title:'System',items:[{href:'/system',icon:Shield,label:'Logic Auditor',desc:'34 rules, auto-fix enabled',color:'text-cyan-400'},{href:'/system',icon:Brain,label:'QA Brain',desc:'19 quality rules',color:'text-purple-400'}]}]
export default function MorePage(){
  return(<div className="px-4 py-4 space-y-6 max-w-2xl mx-auto">
    <div><h1 className="text-2xl font-bold text-white">More</h1><p className="text-white/40 text-sm">All sections & quick links</p></div>
    {sections.map(section=>(<div key={section.title}><div className="text-xs font-semibold text-white/40 uppercase tracking-widest mb-2">{section.title}</div><div className="space-y-1.5">{section.items.map(({href,icon:Icon,label,desc,color})=>(<Link key={href+label} href={href} className="flex items-center gap-3 bg-white/5 border border-white/10 rounded-xl px-3 py-3 active:scale-[0.98] transition-transform"><div className="h-9 w-9 rounded-xl bg-white/5 flex items-center justify-center flex-shrink-0"><Icon className={'h-4 w-4 '+color}/></div><div className="flex-1 min-w-0"><div className="text-sm font-medium text-white">{label}</div><div className="text-[11px] text-white/40">{desc}</div></div></Link>))}</div></div>))}
    <div className="text-center text-[10px] text-white/20 pb-4">BigMike Global Sports CRM · v2.0 · PWA</div>
  </div>)
}