'use client'
import{useSystemHealth,useLogicAuditor,useQABrain,useJarvisIntelligence}from'@/lib/api/hooks'
import{CheckCircle,AlertTriangle,XCircle,Brain,Shield,Zap,RefreshCw}from'lucide-react'
function StatusDot({status}){if(status==='healthy'||status==='ok')return<div className="h-2 w-2 rounded-full bg-green-400"/>;if(status==='warning')return<div className="h-2 w-2 rounded-full bg-yellow-400"/>;return<div className="h-2 w-2 rounded-full bg-red-400 animate-pulse"/>}
export default function SystemPage(){
  const{data:health,isLoading:healthLoading,refetch:refetchHealth}=useSystemHealth()
  const{data:auditor,isLoading:auditorLoading}=useLogicAuditor()
  const{data:qa,isLoading:qaLoading}=useQABrain()
  const{data:jarvis}=useJarvisIntelligence()
  const h=health||{};const a=auditor||{};const q=qa||{}
  const score=q.health_score||h.health_score||0
  return(<div className="px-4 py-4 space-y-4 max-w-2xl mx-auto">
    <div className="flex items-start justify-between"><div><p className="text-[11px] text-cyan-400 uppercase tracking-widest font-medium">System Intelligence</p><h1 className="text-2xl font-bold text-white">System Health</h1></div><button onClick={()=>refetchHealth()} className="p-2 bg-white/5 border border-white/10 rounded-xl active:scale-95"><RefreshCw className="h-4 w-4 text-white/60"/></button></div>
    <div className="bg-white/5 border border-white/10 rounded-xl p-4"><div className="flex items-center justify-between mb-3"><span className="text-sm font-medium text-white/60">Data Quality Score</span><span className={'text-2xl font-bold '+(score>=80?'text-green-400':score>=60?'text-yellow-400':'text-red-400')}>{score}<span className="text-sm text-white/30">/100</span></span></div><div className="h-2 bg-white/10 rounded-full overflow-hidden"><div className={'h-full rounded-full '+(score>=80?'bg-green-400':score>=60?'bg-yellow-400':'bg-red-400')} style={{width:score+'%'}}/></div></div>
    <div className="grid grid-cols-2 gap-2">{healthLoading?[...Array(4)].map((_,i)=><div key={i} className="h-16 bg-white/5 rounded-xl animate-pulse"/>):
      [{label:'JARVIS',icon:Zap,status:h.jarvis_status||'healthy',detail:'AI Briefing Engine'},{label:'Logic Auditor',icon:Shield,status:h.logic_auditor_status||'healthy',detail:(a.rules_count||34)+' rules'},{label:'QA Brain',icon:Brain,status:h.qa_brain_status||'healthy',detail:(q.rules_count||19)+' rules'},{label:'Scheduler',icon:RefreshCw,status:h.scheduler_status||'healthy',detail:(h.jobs_count||38)+'+ jobs'}]
      .map(({label,icon:Icon,status,detail})=>(<div key={label} className="bg-white/5 border border-white/10 rounded-xl p-3"><div className="flex items-center justify-between mb-1.5"><Icon className="h-4 w-4 text-cyan-400"/><StatusDot status={status}/></div><div className="text-sm font-medium text-white">{label}</div><div className="text-[10px] text-white/40">{detail}</div></div>))}
    </div>
    {!auditorLoading&&a.findings?.length>0&&<div><div className="flex items-center justify-between mb-2"><span className="text-xs font-semibold text-white/60 uppercase tracking-wider">Logic Auditor</span><div className="flex gap-1.5 text-[10px]"><span className="bg-green-500/20 text-green-400 px-1.5 py-0.5 rounded">{a.auto_fixed||0} fixed</span><span className="bg-yellow-500/20 text-yellow-400 px-1.5 py-0.5 rounded">{a.queued||0} queued</span></div></div><div className="space-y-1.5">{a.findings.slice(0,5).map((f,i)=>(<div key={i} className="bg-white/5 border border-white/10 rounded-xl px-3 py-2.5 flex items-start gap-2">{f.severity==='error'||f.severity==='high'?<XCircle className="h-4 w-4 text-red-400 mt-0.5 flex-shrink-0"/>:f.severity==='warning'?<AlertTriangle className="h-4 w-4 text-yellow-400 mt-0.5 flex-shrink-0"/>:<CheckCircle className="h-4 w-4 text-green-400 mt-0.5 flex-shrink-0"/>}<div className="flex-1 min-w-0"><div className="text-[11px] font-medium text-white">{f.rule} — {f.title||f.description}</div>{f.detail&&<div className="text-[10px] text-white/40 mt-0.5 line-clamp-2">{f.detail}</div>}</div></div>))}</div></div>}
    {!qaLoading&&q.findings?.length>0&&<div><div className="flex items-center justify-between mb-2"><span className="text-xs font-semibold text-white/60 uppercase tracking-wider">QA Brain</span><span className="text-[10px] text-white/30">{q.findings.length} findings</span></div><div className="space-y-1.5">{q.findings.filter(f=>f.severity==='high'||f.severity==='critical').slice(0,3).map((f,i)=>(<div key={i} className="bg-red-500/10 border border-red-500/20 rounded-xl px-3 py-2.5"><div className="text-[11px] font-medium text-red-300">{f.rule} — {f.title}</div>{f.detail&&<div className="text-[10px] text-white/40 mt-0.5 line-clamp-2">{f.detail}</div>}</div>))}</div></div>}
    {jarvis?.recent_actions?.length>0&&<div><span className="text-xs font-semibold text-white/60 uppercase tracking-wider">Recent JARVIS Actions</span><div className="space-y-1.5 mt-2">{jarvis.recent_actions.slice(0,5).map((action,i)=>(<div key={i} className="flex items-center gap-2 text-[11px] text-white/50 bg-white/5 border border-white/10 rounded-xl px-3 py-2"><Zap className="h-3 w-3 text-blue-400 flex-shrink-0"/><span className="truncate">{action.description||action.action}</span></div>))}</div></div>}
  </div>)
}